### PR TITLE
Change behaviour such that the owner is set from the IAM user_id. 

### PR DESCRIPTION
**Pull request by tmgstevens**
Can still be overridden if needed

### CODE REVIEW

**Review by StephanDollberg — APPROVED** [review]
Changing from hardcoded seems to make sense to me in any case.

Note that we do it slightly differently on our internal terraform but I am not sure whether one or the other is better:

```
# we extract the IAM username by getting the caller identity as an ARN
# then extracting the resource protion, which gives something like
# user/travis.downs, and finally we strip the user/ part to use as a tag
data "aws_caller_identity" "current" {}

data "aws_arn" "caller_arn" {
  arn = data.aws_caller_identity.current.arn
}
```
and then
```
    iam_username : trimprefix(data.aws_arn.caller_arn.resource, "user/")
```

**Comment by tmgstevens** [comment]
Thanks @StephanDollberg .
Tried the other way quickly and it gives me: `owner" = "assumed-role/AWSReservedSSO_AWSAdministratorAccess_cd955a4c8ba86395/<myemail>@redpanda.com"`
I'll leave as is.

**Comment by travisdowns** [comment]
Yeah this looks better, can't remember why I chose the arn/trimprefix route in the first place. It was pre-SSO and worked OK then.

Does this approach just result in the email address as the tag?

**Comment by tmgstevens** [comment]
No, not quite - mine comes in at `AROA6ODABCDSRWG3SHIH:<myemail>@redpanda.com`
So we could split on the colon I guess

**Pull request merged**
